#define OFFSET_ACTOR_ID 0x18//
#define OFFSET_UWORLD 0x7DCDDC8//
#define OFFSET_CACHED_LOCALPLAYER 0x808CBA0 //localplayer //
#define OFFSET_GNAMES 0x8079778//
#define OFFSET_GNAME_SIZE 0x0010 //
#define OFFSET_DECRYPT 0x6D48F28 //
#define OFFSET_CHUNKSIZE 0x40C4 //
#define OFFSET_PERSISTENT_LEVEL 0x6D8 //
#define OFFSET_ACTORS_ARRAY 0x1B8 //
#define OFFSET_MESHCOMPONENT_COMPONENT2WORLD 0x2B0//

#define OFFSET_CAMERA_LOCATION 0x9B4//
#define OFFSET_CAMERA_ROTATION 0x9C0//
#define OFFSET_CAMERA_FOV 0x9B0 //

#define OFFSET_MESHCOMPONENT_UANIMINSTANCE 0xC88//
#define OFFSET_UANIMINSTANCE_CONTROL_ROTATION_CP 0x6B0//
#define OFFSET_UANIMINSTANCE_RECOILADS_ROTATION 0x8DC//
#define OFFSET_LOCALPLAYER_CONTROLLER 0x48 //
#define OFFSET_CONTROLLER_ROTATION 0x278 //
#define OFFSET_CONTROLLER_INPUTROT 0x2C0 //
#define OFFSET_CONTROLLER_ACKPAWN 0x450//
#define OFFSET_SPECTATOR_COUNT 0x1734//
#define OFFSET_LOCALPLAYER_CAMERA 0x4A8//
#define OFFSET_PLAYER_CHARACTORNAME 0xED0
#define OFFSET_PLAYER_HEALTH 0xFE8//
#define OFFSET_PLAYER_GROGGYHEALTH 0x1128////
#define OFFSET_PLAYER_TEAMID 0xCD0 //
#define OFFSET_ACTOR_ROOTCOMPONENT 0x1C8//
#define OFFSET_ROOTCOMPONENT_VELOCITY 0x2E0
#define OFFSET_ACTOR_MESHCOMPONENT 0x538//
#define OFFSET_MESHCOMPONENT_STATICMESH 0xAE0 //BoneArray //
#define OFFSET_MESHCOMPONENT_LASTSUBMITTIME 0x780//
#define OFFSET_MESHCOMPONENT_LASTRENDERTIMEONSCREEN 0x788 //
#define OFFSET_ROOTCOMPONENT_LOCATION (OFFSET_MESHCOMPONENT_COMPONENT2WORLD + 0x10) //
#define OFFSET_LOCALPLAYER_WEAPONPROCESSOR 0x0EB8//
#define OFFSET_WEAPONPROCESSER_EQUIPPEDWEAPONS 0x2B8 //
#define OFFSET_WEAPONPROCESSER_WEAPONINDEX (OFFSET_WEAPONPROCESSER_EQUIPPEDWEAPONS + 0x21)//
#define OFFSET_WEAPON_TRAJECTORYDATA 0xF38 //
#define OFFSET_TRAJECTORYDATA_CONFIG 0xEF8//
#define OFFSET_TRAJECTORYCONFIG_VELOCITY (OFFSET_TRAJECTORYDATA_CONFIG + 0x0)//
#define OFFSET_TRAJECTORYCONFIG_VDRAG_COEFICIENT (OFFSET_TRAJECTORYDATA_CONFIG + 0x2C)//